### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by dejavu51** [HirbodBehnam/Shadowsocks-Cloak-Installer#46]
Hi, I just installed this using the script command provided with all default options, and everything is working allright. I was checking the config files in /etc/cloak and noticed that in both "ckadminclient.json" and "shadowsocks.json" , the "EncryptionMethod" is set to "plain". So is the encryption off by default or did I do something wrong? if there is anyway to increase the security please advise. thank you

**Comment by HirbodBehnam** [comment]
Hello
`ckadminclient.json` is only used by admin panel of the script so it does not need encryption at all.
For shadowsocks, from cloak's documentation, it says that it does not need encryption because shadowsocks itself encrypts its packets.
I'd also like to note that encryption is configured from client. So your clients can turn it on or off without needing you to do anything from server.

**Comment by dejavu51** [comment]
Thanks for the explanation. I found this article about china firewall being able to detect shadowsocks [https://gfw.report/talks/imc20/en/](url) , So I turned the cloak encryption on too just to be sure.
