### ISSUE TITLE
On Android works but doesn't work on windows 10

### ISSUE THREAD

**Issue by ayton** [HirbodBehnam/Shadowsocks-Cloak-Installer#8]
I use Shadowsocks-4.1.7.1 on windows 10, configured according to this instructions:

Windows
At first install shadowsocks windows. Then download cloak for windows from here. If you are using a 32-bit system, download ck-client-windows-386-X.exe if your system is 64-bit use ck-client-windows-amd64-X.exe. Then use the QR Code or ss:// link to import the server.

The program will give you an error that shadowsocks cannot find ck-client or something like this. Click OK and go to Edit Servers. Then write the absolute path to ck-client file in Plugin Program.

please see the screenshot: http://prntscr.com/p6qroa
but no connection.
What am I doing wrong?

**Comment by HirbodBehnam** [comment]
Hello
The problem is that somehow the Plugin Options is empty.
This is my config file for example:
![image](https://user-images.githubusercontent.com/11520090/64954480-f2b4a900-d89a-11e9-9b53-c47c84f7052f.png)
Can you check that the `ss://` link matches this path:
```
ss://YWVzLTEyOC1nY206VVhRQ1Joa1VxRThBd1d6Vg==@1.1.1.1:443?plugin=ck-client%3BUID%3DN33tBXC4tnbN2ytSXEeg6A%5C%3D%5C%3D%3BPublicKey%3DV3L0MPV%2BK0XNwOkEQr3dzHbAbmpzHpUJxWqhvxALjQ4%5C%3D%3BServerName%3Dbing.com%3BBrowserSig%3Dchrome%3BNumConn%3D4%3BProxyMethod%3Dshadowsocks%3BEncryptionMethod%3Dplain
```
I mean you should see `PublicKey`, `UID` and these stuff in the ss link. If you can see them try again with the ss link.

If this one didn't work either, use the QR code that the android application creates for you.

**Comment by ayton** [comment]
Thanks for the quick feedback, problem solved.
